config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :reviews do
    resources :likes, only: [:create, :destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get    '/login' => 'user_sessions#new', as: :login
  post   '/login' => 'user_sessions#create'
  delete '/logout' => 'user_sessions#destroy', as: :logout
  post   '/logout' => 'user_sessions#destroy'
  get    '/users/:id/edit' => 'users#edit'
  get    '/books/search' => 'books#search'
 
  # post   '/reviews/new' => 'reviews#new' 
  get '/reviews/:book_id/new' => 'reviews#new', as:'reviews_new'
  post '/reviews/:book_id/create' => 'reviews#create', as:'reviews_create'

  get '/reviews/tag_list/:id' => 'reviews#index'

  root 'user_sessions#new'
# root 'reviews#new'  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  self.primary_key = "isbn" #isbnでデータを一意に識別
  has_many :reviews, dependent: :destroy #親モデルに紐づく子モデルも削除できる。ex)ユーザ退会でコメントも消える
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :review
  belongs_to :user
  validates_uniqueness_of :review_id, scope: :user_id #review_idとuser_idの組が1組だけ
end

app/models/review.rb
class Review < ApplicationRecord
  acts_as_taggable
  belongs_to :user
  belongs_to :book, primary_key: "isbn"
  validates :content, {presence: true, length: {maximum: 50} }
  
  has_many :likes
  has_many :liked_users, through: :likes, source: :user
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!
  
  validates :email, presence: true, uniqueness: true
  validates :password, length: { minimum: 4 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }
  
  has_many :reviews, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_reviews, through: :likes, source: :review
  has_secure_password
  
  def already_liked?(review) #ユーザーがすでに投稿に対していいねしているか判定
    self.likes.exists?(review_id: review.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :require_login #sorceryが作成するメソッド。ログインしてない時not_authenticatedメソッドを発火する
  protect_from_forgery with: :exception

  add_flash_types :success, :info, :warning, :danger
  
  def not_authenticated
    redirect_to login_url
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def search
    @books = [] #空の配列。APIから取得したJSONデータをここに格納
    @title = params[:title]
    
    genre = RakutenWebService::Books::Genre.search({ booksGenreId: '001' })
    @genres = genre.first["children"].map{|v| {
      id: v["booksGenreId"],
      name: v["booksGenreName"]
    }}
    
    if @title.present?
      results = RakutenWebService::Books::Book.search({
        title: @title,
      })
      results.each do |result| #@booksにAPIから取得したデータを格納。
        book = Book.new(read(result)) #read(result)は下記privateで絞り込んだAPIデータを@booksに格納
        @books << book
      end
    
      @books.each do |book| #@book内のデータを格納
        unless Book.all.include?(book) #unlessで既に保存した本は除外する
          book.save
        end
      end
    end
    
    if params[:book_genre_id]
      @books = Book.where('book_genre_id like ?', "#{params[:book_genre_id]}%")
    end
  end
  
      # binding.pry
  
  private #class内でのみアクセス可能
  def read(result) #楽天APIから取得したデータの絞り込み（タイトル、著者名、URL、ISBN、画像、ジャンル、商品説明）
    title = result["title"]
    author = result["author"]
    url = result["itemUrl"]
    isbn = result["isbn"]
    image_url = result["mediumImageUrl"]#.gsub('?_ex=120x120', '') 
    book_genre_id = result["booksGenreId"] #ジャンル
    {
      title: title, #ハッシュ。対応するカラムにデータを格納？
      author: author,
      url: url,
      isbn: isbn,
      image_url: image_url,
      book_genre_id: book_genre_id,
    }
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = current_user.likes.create(review_id: params[:review_id])
    redirect_back(fallback_location: reviews_path)
  end

  def destroy
    @like = Like.find_by(review_id: params[:review_id], user_id: current_user.id)
    @like.destroy
    redirect_back(fallback_location: reviews_path)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    @book = Book.find_by(isbn: params[:isbn]) #createのindexアクションへのリダイレクトでisbnという名前でbook_id渡すためparams[:isbn]
    @reviews = Review.all.order(created_at: "DESC") #更新順に表示
    @ranks = Review.find(Like.group(:review_id).order("count(review_id) DESC").pluck(:review_id)) #いいね多い順に表示
    
    if params[:tag_name]
      @reviews = Review.tagged_with("#{params[:tag_name]}")
    end
    # binding.pry
  end
  
  def new
    @book = Book.find_by(isbn: params[:book_id])
    @review = Review.new
  end
  
  def show
    @review = Review.find(params[:id])
    @book = @review.book
  end
  
  def create
    @book = Book.find_by(isbn: params[:book_id])
    @review = current_user.reviews.new(review_params)
    if @review.save
      # @review.save_tag(tag_list)
      redirect_to reviews_path(isbn: params[:book_id]), notice: "レビューに成功しました"
    else
      flash.now[:danger] = "レビューに失敗しました"
      render :new
    end
  end
  
  private
  def review_params
    params.require(:review).permit(:content, :book_id, :tag_list)
  end
  
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, except: [:destroy]
  
  def index
    @user = User.new
  end
  
  def new
    @user = User.new
  end


  def create
    @user = login(params[:email], params[:password])
    if @user
      redirect_back_or_to root_path, success: "ログインに成功しました"
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render action: 'new'
    end
  end

  def destroy
    logout
    redirect_to(:users, notice: 'ログアウトしました')
  end
  
  private
  def log_in(user)
    session[:user_id] = user.id
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
    @user = User.find(params[:id])       
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)
      if @user.save
        redirect_to root_path, success: '登録が完了しました'
        # format.html { redirect_to @user, success: "登録が完了しました" }
        # format.json { render :show, status: :created, location: @user }
      else
        # format.html { render :new, status: :unprocessable_entity }
        # format.json { render json: @user.errors, status: :unprocessable_entity }
        flash.now[:danger] = "登録に失敗しました"
        render :new
      end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/search.html.erb
<p>本のタイトルで検索</p>
<%= form_tag(books_search_path, method: :get) do %> <!--検索入力フォーム-->
  <%= text_field_tag :title, @title %> <!--タイトル入力テキストボックス-->
  <%= button_tag type: "submit" %>

<p>本のジャンルで検索</p>
  <% @genres.each do |genre| %>
    <%= link_to genre[:name], books_search_path(book_genre_id: genre[:id]) %>
  <% end %>
<% end %>
<!--検索結果の表示（画像、タイトル、著者名、商品説明）-->
 <!--link_toメソッドとネスト(do〜end)でタイトル等クリックできる-->
<% if @books %>
  <% @books.each do |book| %>
    <%= link_to reviews_new_path(book_id: book.id) do %> 
      <%= image_tag book.image_url %>
      <%= book.title %>
      <%= book.author%>
    <% end %>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookband</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
   <div id="nav">
     <% if current_user %>
       <%= link_to "Edit Profile", edit_user_path(current_user.id) %>
       <%= link_to "Logout", :logout, method: :post %>
     <% else %>
       <%= link_to "Register", new_user_path %> |
       <%= link_to "Login", :login %>
     <% end %>
   </div>
   <div>
   </div>
   <% flash.each do |key, value| %>
     <div class="alert alert-<%= key %>" role="alert"><%= value %></div>
   <% end %>
   
   <%= yield %>
   
     <script>
       $(function(){
         $(".alert")fadeOut(3000);
       });
     </script>
  </body>
</html>

app/views/reviews/_tag_list.html.erb
<% tag_list.each do |tag| %>
  <%= link_to tag, reviews_path(tag_name: tag, isbn: isbn), class: "text-white" %>
<% end %>

app/views/reviews/index.html.erb
<h1>レビュー一覧</h1>

<p><%= @book.title %></p>
<p><%= @book.author %></p>
<p><%= image_tag @book.image_url %></p>

<%= @ranks.each do |review| %>
  <a href="/users/<%= review.user.id %>"><%= review.user.email %></a>
  <p><a href="/reviews/<%= review.id %>"><%= review.content %></a><%= review.liked_users.count %></p>
  <%= render 'reviews/tag_list', tag_list: review.tag_list, isbn: review.book.isbn %>
<% end %>

<%= @reviews.each do |review| %>
  <a href="/users/<%= review.user.id %>"><%= review.user.email %></a>
  <p><a href="/reviews/<%= review.id %>"><%= review.content %></a><%= review.liked_users.count %></p>
  <%= render 'reviews/tag_list', tag_list: review.tag_list, isbn: review.book.isbn %>

<% end %>

app/views/reviews/new.html.erb
<h1>レビュー記入ページ</h1>

<!--選択した本タイトル、画像、著者名表示-->
<p><%= @book.title %></p>
<p><%= @book.author %></p>
<p><%= image_tag @book.image_url %></p>

<!--レビュー記入-->
<%= form_for @review,url: reviews_create_path(book_id: @book.id) do |form| %>
     <div class="form-group">
        <%= form.text_area :content %>
        <%= form.hidden_field :book_id, :value => @book.id %>
     </div>
      
     <div class="form-group">
        <%= form.label :tag_list %>
        <%= form.text_field :tag_list, :value => @review.tag_list.join(','), class: "form-control" %> <!--join=>配列を','を挟んで表示-->
     </div>
     
     <%= form.submit 'レビューを投稿' %>
     
     <%= flash[:notice] %>
     <%= flash[:success] %>
     <%= flash[:danger] %>
<% end %>

<%= link_to '戻る', books_search_path %>
<%= link_to 'レビュー一覧', reviews_path %>

app/views/reviews/show.html.erb
<h1>レビュー詳細ページ</h1>

<p><%= @book.title %></p>
<p><%= @book.author %></p>
<p><%= image_tag @book.image_url %></p>

<h3><%= @review.user.email %></h3>
<h3><%= @review.content %></h3>



<h3>いいね件数: <%= @review.likes.count %></h3>
<% if current_user.already_liked?(@review) %>
  <%= button_to 'いいねを取り消す', review_like_path(@review), method: :delete %>
<% else %>
  <%= button_to 'いいね', review_likes_path(@review) %>
<% end %>

<h3>いいねしたユーザー</h3>
<% @review.liked_users.each do |user| %>
  <li><%= user.email %></li>
<% end %>

<%= link_to "レビュー一覧へ戻る", reviews_path %>

app/views/user_sessions/create.html.erb
<h1>UserSessions#create</h1>
<p>Find me in app/views/user_sessions/create.html.erb</p>

app/views/user_sessions/destroy.html.erb
<h1>UserSessions#destroy</h1>
<p>Find me in app/views/user_sessions/destroy.html.erb</p>

app/views/user_sessions/index.html.erb
<div class="top-hero-wrapper text-center">
  <div class="container top-hero-container">
    <h1 class="text-white">Bookband(仮)</h1>
    <h2 class="text-white">Bookband is a service that you can share book reviews.</h2>
    <div class="row">
      <div class="col-md-offset-3 col-md-3">
        <%= link_to '新規登録', new_user_path, method: :get, class: 'btn btn-block btn-white' %>
      </div>
      <div class="col-md-3">
        <%= link_to 'ログイン', login_path, method: :get,class: 'btn btn-block btn-white' %>
      </div>
    </div>
  </div>
</div>

app/views/user_sessions/new.html.erb
<div class="users-new-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-offset-4 col-md-4 users-new-container">
        <h1 class="text-center text-white">ログイン</h1>
        
        <%= form_for :session, url: login_path do |f| %>
          <div class="form-group">
            <%= f.label :email, class: 'text-white' %>
            <%= f.text_field :email, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :password, class: 'text-white' %>
            <%= f.text_field :password, class: 'form-control' %>
          </div>
          <div class= "action">
            <%= f.submit "ログイン",class: 'btn-block btn-white' %>
          </div>
        <% end %>
        
      </div>
    </div>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="users-new-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-offset-4 col-md-4 users-new-container">
        <h1 class="text-center text-white">ユーザー編集</h1>
        
        <%= form_for @user do |f| %>
          <div class="form-group">
            <%= f.label :email, class: 'text-white' %>
            <%= f.text_field :email, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :password, class: 'text-white' %>
            <%= f.text_field :password, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :password_confirmation, class: 'text-white' %>
            <%= f.text_field :password_confirmation, class: 'form-control' %>
          </div>
          <%= f.submit "登録",class: 'btn-block btn-white' %>
        <% end %>
        
        <%= link_to 'Show', @user,class: 'text-white' %> 
        <%= link_to '戻る', users_path,class: 'text-white' %>
        
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="users-new-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-offset-4 col-md-4 users-new-container">
        <h1 class="text-center text-white">Users</h1>
        
          <p id="notice"><%= notice %></p>
                <div class= "action">
                  <%= link_to 'ユーザー新規作成', new_user_path, class: 'btn-block btn-white' %>
                  <%= link_to '本の検索', books_search_path, class: 'btn-block btn-white' %>
                </div>
                <br>
            <tbody>
              <% @users.each do |user| %>
                <tr>
                  <td><%= user.email %></td>
                  <td><%= link_to 'Show', user %></td>
                  <td><%= link_to '編集', edit_user_path(user) %></td>
                  <td><%= link_to '削除', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="users-new-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-offset-4 col-md-4 users-new-container">
        <h1 class="text-center text-white">新規登録</h1>
        
        <%= form_for @user do |f| %>
          <div class="form-group">
            <%= f.label :email, class: 'text-white' %>
            <%= f.text_field :email, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :password, class: 'text-white' %>
            <%= f.text_field :password, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :password_confirmation, class: 'text-white' %>
            <%= f.text_field :password_confirmation, class: 'form-control' %>
          </div>
          <%= f.submit "登録",class: 'btn-block btn-white' %>
        <% end %>
        <%= link_to 'ログインはこちら', login_path, method: :get,class: 'text-white' %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<h1>ユーザー詳細ページ</h1>
<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<h2>投稿内容</h2>
<% @user.reviews.each do |review| %>
  <a href="/reviews/<%= review.id %>"><%= review.content %></a>
  <hr>
<% end %>

<h3>いいねしている投稿</h3>
<% @user.liked_reviews.each do |review| %>
  <%= review.user.email %>
  <%= review.content %>
<% end %>

<%= link_to '編集', edit_user_path(@user) %> |
<%= link_to '戻る', users_path %>